---

version: 3

# build_arg_defaults:
#   ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  python: requirements.txt
  galaxy: requirements.yml

additional_build_steps:
  append_base:
    - RUN yum upgrade -y
    - RUN yum install -y python3
    - RUN yum install -y python3-pip
    - RUN yum install -y krb5-devel
    - RUN yum install -y krb5-libs
    - RUN yum install -y krb5-workstation
    - RUN yum install -y python3-devel
    - RUN yum install -y gcc
    - RUN yum install -y epel-release
    - RUN yum install -y openssh-server openssh-clients iputils
    - RUN python3 -m pip install --upgrade --force pip ansible-core ansible-runner ansible-lint
