---
collections:

  - name: ansible.netcommon             
    version: 6.1.0

  - name: ansible.utils
    version: 4.1.0

  - name: cisco.aci
    version: 2.8.0

  - name: cisco.nxos
    version: 4.4.0

  - name: cisco.ios
    version: 6.0.0

  - name: cisco.ucs
    version: 1.10.0

  - name: netbox.netbox
    version: 3.15.0

  - name: paloaltonetworks.panos
    version: 2.17.3 

  - name: arista.eos
    version: 9.0.0