

name: 'Ansible Runner'
 
on:
  push:
 
jobs:
  run_ansible:

    name: 'Runs Ansible Container'
    runs-on: ubuntu-latest

    container:
        image: 'rowco/ansible-netops:latest'
        volumes:
            - ${{ github.workspace }}:/runner

    steps:
      - run: |
            ansible-lint

